name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Hugging Face CLI
      run: |
        pip install huggingface_hub
        echo ${{ secrets.HF_TOKEN }} > ~/.huggingface/token
        huggingface-cli login --token ${{ secrets.HF_TOKEN }}
    
    - name: Configure Git authentication
      run: |
        git config --global user.name "nkofficial-1005"
        git config --global user.email "nikita.datascience@gmail.com"
        git remote add hf https://huggingface.co/spaces/kohlin/legal-chatbot
        git remote set-url hf https://huggingface.co/${{ secrets.HF_TOKEN }}@huggingface.co/spaces/kohlin/legal-chatbot

    - name: Push to Hugging Face Spaces
      run: |
        git push hf main
