name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch full history to avoid shallow update issues

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Set up Hugging Face CLI
      run: |
        pip install huggingface_hub
        mkdir -p ~/.huggingface
        echo ${{ secrets.HF_TOKEN }} > ~/.huggingface/token
        huggingface-cli login --token ${{ secrets.HF_TOKEN }}

    - name: Configure Git for Hugging Face
      run: |
        git config --global user.name "nkofficial-1005"
        git config --global user.email "nikita.datascience@gmail.com"
        git remote add hf https://huggingface.co/spaces/kohlin/legal-chatbot || true
        git remote set-url hf https://kohlin:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/kohlin/legal-chatbot

    - name: Set up Git LFS (if needed)
      run: |
        git lfs install
        git lfs pull hf main || true

    - name: Pull changes from Hugging Face Space (merge histories)
      run: |
        git pull hf main --allow-unrelated-histories --no-rebase || true

    - name: Push code to Hugging Face Space
      run: |
        git push hf main --force-with-lease
      env:
        HUGGINGFACE_TOKEN: ${{ secrets.HF_TOKEN }}
