name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Set up Hugging Face CLI
      run: |
        pip install huggingface_hub
        mkdir -p ~/.huggingface
        echo ${{ secrets.HF_TOKEN }} > ~/.huggingface/token
        huggingface-cli login --token ${{ secrets.HF_TOKEN }}

    - name: Configure Git authentication for Hugging Face
      run: |
        git config --global user.name "nkofficial-1005"
        git config --global user.email "nikita.datascience@gmail.com"
        git remote add hf https://huggingface.co/spaces/kohlin/legal-chatbot
        git remote set-url hf https://$HUGGINGFACE_USERNAME:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/kohlin/legal-chatbot
    
    - name: Push to Hugging Face Spaces
      run: |
        git push hf main
