name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main  # Or replace with master if your default branch is master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Hugging Face CLI
      run: |
        pip install huggingface_hub
        huggingface-cli login --token ${{ secrets.HF_TOKEN }}
        
    - name: Push to Hugging Face Spaces
      run: |
        git remote add hf https://huggingface.co/spaces/kohlin/legal-chatbot
        git push hf main